on:
  pull_request:
  push:
jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
    - uses: nixbuild/nix-quick-install-action@63ca48f939ee3b8d835f4126562537df0fee5b91 # v32
    - uses: nix-community/cache-nix-action@135667ec418502fa5a3598af6fb9eb733888ce6a # 6.1.3
      with:
        # restore and save a cache using this key
        primary-key: nix-${{ runner.os }}-${{ runner.arch }}-check-${{ hashFiles('**/*.nix', '**/flake.lock', '**.*.tf') }}
        # if there's no cache hit, restore a cache by this prefix
        restore-prefixes-first-match: |
          nix-${{ runner.os }}-${{ runner.arch }}-check-
    - run: |
        nix flake check
        nix run .#check
